<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit-no">

    <link rel="stylesheet" href="public/css/bootstrap.min.css">

    <title>Previsão do Tempo</title>
</head>
<body>
   <h1>Temperaturas Elevadas - Nordeste de MG </h1>
    <div class="container">
        <ul>
            <?php foreach($noticias as $noticia) { ?>
                <li><a href=" <?php echo 'http://localhost/portal/previsaotempo/previsaotempo/' .?>"><?php echo $noticia['titulo_url']; ?> </a> </li>  
            <?php } ?>
            </ul>
    
</body>
</html>